Crowdin/src/Entity/Language.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LanguageRepository")
 */
class Language
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */

    private $language_name;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", mappedBy="languages")
     */
    private $users;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Project", mappedBy="language_id")
     */
    private $projects;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TraductionTarget", mappedBy="language_id", orphanRemoval=true)
     */
    private $traductionTargets;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->projects = new ArrayCollection();
        $this->traductionTargets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLanguageName(): ?string
    {
        return $this->language_name;
    }

    public function setLanguageName(string $language_name): self
    {
        $this->language_name = $language_name;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addLanguage($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->contains($user)) {
            $this->users->removeElement($user);
            $user->removeLanguage($this);
        }

        return $this;
    }

    /**
     * @return Collection|Project[]
     */
    public function getProjects(): Collection
    {
        return $this->projects;
    }

    public function addProject(Project $project): self
    {
        if (!$this->projects->contains($project)) {
            $this->projects[] = $project;
            $project->setLanguageId($this);
        }

        return $this;
    }

    public function removeProject(Project $project): self
    {
        if ($this->projects->contains($project)) {
            $this->projects->removeElement($project);
            // set the owning side to null (unless already changed)
            if ($project->getLanguageId() === $this) {
                $project->setLanguageId(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|TraductionTarget[]
     */
    public function getTraductionTargets(): Collection
    {
        return $this->traductionTargets;
    }

    public function addTraductionTarget(TraductionTarget $traductionTarget): self
    {
        if (!$this->traductionTargets->contains($traductionTarget)) {
            $this->traductionTargets[] = $traductionTarget;
            $traductionTarget->setLanguageId($this);
        }

        return $this;
    }

    public function removeTraductionTarget(TraductionTarget $traductionTarget): self
    {
        if ($this->traductionTargets->contains($traductionTarget)) {
            $this->traductionTargets->removeElement($traductionTarget);
            // set the owning side to null (unless already changed)
            if ($traductionTarget->getLanguageId() === $this) {
                $traductionTarget->setLanguageId(null);
            }
        }

        return $this;
	}
	
	public function __toString()
    {
        return $this->language_name;
    }
}

Crowdin/src/Entity/Project.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProjectRepository")
 */
class Project
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url;

      /**
     * @ORM\Column(type="string",  nullable=true)
     */
    private $file;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="projects")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Language", inversedBy="projects")
     * @ORM\JoinColumn(nullable=false)
     */
    private $language;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TraductionSource", mappedBy="project", orphanRemoval=true)
     */
    private $traductionSources;

    public function __construct()
    {
        $this->traductionSources = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getFileName(): ?string
    {
        return $this->file;
    }

    public function setFileName(string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getLanguageId(): ?Language
    {
        return $this->language;
    }

    public function setLanguageId(?Language $language): self
    {
        $this->language = $language;

        return $this;
	}
	

    public function getLanguage(): ?Language
    {
        return $this->language;
    }

    public function setLanguage(?Language $language): self
    {
        $this->language = $language;

        return $this;
    }

    /**
     * @return Collection|TraductionSource[]
     */
    public function getTraductionSources(): Collection
    {
        return $this->traductionSources;
    }

    public function addTraductionSource(TraductionSource $traductionSource): self
    {
        if (!$this->traductionSources->contains($traductionSource)) {
            $this->traductionSources[] = $traductionSource;
            $traductionSource->setProjectId($this);
        }

        return $this;
    }

    public function removeTraductionSource(TraductionSource $traductionSource): self
    {
        if ($this->traductionSources->contains($traductionSource)) {
            $this->traductionSources->removeElement($traductionSource);
            // set the owning side to null (unless already changed)
            if ($traductionSource->getProjectId() === $this) {
                $traductionSource->setProjectId(null);
            }
        }

        return $this;
	}
	
	public function __toString()
    {
        return $this->name;
    }
}

Crowdin/src/Entity/TraductionSource.php
<?php

namespace App\Entity;

use App\Entity\Project;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TraductionSourceRepository")
 */
class TraductionSource
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Project", inversedBy="traductionSources")
     * @ORM\JoinColumn(nullable=false)
     */
    private $project;

    /**
     * @ORM\Column(type="string", length=255,  nullable=true)
     */
	private $source;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TraductionTarget", mappedBy="traduction_source", orphanRemoval=true)
     */
    private $traductionTargets;

    public function __construct()
    {
        $this->traductionTargets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProjectId(): ?Project
    {
        return $this->project;
    }

    public function setProjectId(?Project $project): self
    {
        $this->project = $project;

        return $this;
	}
	
	public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): self
    {
        $this->project = $project;

        return $this;
    }

    public function getSource(): ?string
    {
        return $this->source;
    }

    public function setSource(string $source): self
    {
        $this->source = $source;

        return $this;
	}


    /**
     * @return Collection|TraductionTarget[]
     */
    public function getTraductionTargets(): Collection
    {
        return $this->traductionTargets;
    }

    public function addTraductionTarget(TraductionTarget $traductionTarget): self
    {
        if (!$this->traductionTargets->contains($traductionTarget)) {
            $this->traductionTargets[] = $traductionTarget;
            $traductionTarget->setTraductionSourceId($this);
        }

        return $this;
    }

    public function removeTraductionTarget(TraductionTarget $traductionTarget): self
    {
        if ($this->traductionTargets->contains($traductionTarget)) {
            $this->traductionTargets->removeElement($traductionTarget);
            // set the owning side to null (unless already changed)
            if ($traductionTarget->getTraductionSourceId() === $this) {
                $traductionTarget->setTraductionSourceId(null);
            }
        }

        return $this;
	}
	public function __toString()
    {
        return $this->source;
    }

}

Crowdin/src/Form/TraductionSourceType.php
<?php

namespace App\Form;

use App\Entity\TraductionSource;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;

class TraductionSourceType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('source');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => TraductionSource::class,
        ]);
    }
}

Crowdin/src/Controller/TraductionSourceController.php
<?php

namespace App\Controller;

use App\Entity\TraductionSource;
use App\Entity\Project;
use App\Manager\TraductionSourceManager;
use App\Form\TraductionSourceType;
use App\Form\TraductionSourceCSVType;
use App\Repository\TraductionSourceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use League\Csv\Reader;
use Knp\Component\Pager\PaginatorInterface;



/**
 * @Route("/traduction/source")
 */
class TraductionSourceController extends AbstractController
{
	/**
	 * @Route("/", name="traduction_source_index", methods={"GET"})
	 */
	public function index(TraductionSourceRepository $repository, Request $request, PaginatorInterface $paginator): Response
	{

		$data =  $repository->findAll();
		$traductionSources = $paginator->paginate(
			$data, // Requête contenant les données à paginer (ici nos articles)
			$request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
			20 // Nombre de résultats par page
		);

		return $this->render('traduction_source/index.html.twig', [
			'traduction_sources' => $traductionSources
		]);
	}

	/**
	 * @Route("/new/{id}", name="traduction_source_new", methods={"GET","POST"})
	 * 
	 */
	public function new(Project $project, Request $request, TraductionSourceManager $manager): Response
	{
		$this->denyAccessUnlessGranted('create', $project);
		$traductionSource = new TraductionSource();
		$traductionSource->setProjectId($project);
		$form = $this->createForm(TraductionSourceType::class, $traductionSource);
		$form->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {
			$manager->add($traductionSource);
			$manager->save();

			return $this->redirectToRoute('traduction_source_index');
		}

		return $this->render('traduction_source/new.html.twig', [
			'traduction_source' => $traductionSource,
			'form' => $form->createView(),
		]);
	}

	/**
	 * @Route("/newCSV/{id}", name="traduction_source_CSV_new", methods={"GET","POST"})
	 * 
	 */
	public function newCSV(Project $project, Request $request, TraductionSourceManager $manager): Response
	{
		$this->denyAccessUnlessGranted('create', $project);
		$traductionSource = new TraductionSource();
		$form = $this->createForm(TraductionSourceCSVType::class, $traductionSource);
		$form->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {
			$file = $form['file']->getData();

			if ($file) {
				$originalFilename = pathinfo($file->getClientOriginalName(), PATHINFO_FILENAME);
				// this is needed to safely include the file name as part of the URL
				$newFilename = $originalFilename . '-' . uniqid() . '.' . 'csv';

				// Move the file to the directory where brochures are stored
				try {
					$file->move(
						$this->getParameter('files_directory'),
						$newFilename
					);
				} catch (FileException $e) {
					// ... handle exception if something happens during file upload
				}

				// updates the 'brochureFilename' property to store the PDF file name
				// instead of its contents
				$project->setFilename($newFilename);
			}
			$results = Reader::createFromPath($this->getParameter('files_directory') . $project->getFileName());
			$results->setHeaderOffset(0);

			foreach ($results as $row) {

				// create new athlete
				$traductionSource = new TraductionSource();
				$traductionSource->setProjectId($project);
				$traductionSource->setSource($row['source']);

				$manager->add($traductionSource);
			}

			$manager->save();

			return $this->redirectToRoute('traduction_source_index');
		}

		return $this->render('traduction_source/newCSV.html.twig', [
			'traduction_source' => $traductionSource,
			'form' => $form->createView(),
		]);
	}

	/**
	 * @Route("/{id}", name="traduction_source_show", methods={"GET"})
	 */
	public function show(TraductionSource $traductionSource): Response
	{
		return $this->render('traduction_source/show.html.twig', [
			'traduction_source' => $traductionSource,
		]);
	}
	

	/**
	 * @Route("/{id}/edit", name="traduction_source_edit", methods={"GET","POST"})
	 */
	public function edit(Request $request, TraductionSource $traductionSource, TraductionSourceManager $manager): Response
	{
		$this->denyAccessUnlessGranted('edit', $traductionSource);
		$form = $this->createForm(TraductionSourceType::class, $traductionSource);
		$form->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {
			$manager->save();

			return $this->redirectToRoute('traduction_source_index');
		}

		return $this->render('traduction_source/edit.html.twig', [
			'traduction_source' => $traductionSource,
			'form' => $form->createView(),
		]);
	}

	/**
	 * @Route("/{id}", name="traduction_source_delete", methods={"DELETE"})
	 */
	public function delete(Request $request, TraductionSource $traductionSource, TraductionSourceManager $manager): Response
	{
		$this->denyAccessUnlessGranted('delete', $traductionSource);
		if ($this->isCsrfTokenValid('delete' . $traductionSource->getId(), $request->request->get('_token'))) {
			$manager->delete($traductionSource);
			$manager->save();
		}

		return $this->redirectToRoute('traduction_source_index');
	}
}

/*
 	$reader = Reader::createFromPath('%kernel.root_dir%/../public/uploads/files/%$newFilename%');
			$results = $reader->fetchAssoc();

			foreach ($results as $row) {

				// create new athlete
				$traductionSource = new TraductionSource();
				$traductionSource->setProjectId($project);
				$traductionSource->setSource($row['source']);
	
				$traductionSourceManager->add($traductionSource);
				
			}
	
			$traductionSourceManager->save();
			*/

Crowdin/templates/traduction_source/_delete_form.html.twig
<form method="post" action="{{ path('traduction_source_delete', {'id': traduction_source.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ traduction_source.id) }}">
    <button class="btn">Delete</button>
</form>

Crowdin/templates/traduction_source/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Crowdin/templates/traduction_source/_formCSV.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Crowdin/templates/traduction_source/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit TraductionSource{% endblock %}

{% block body %}
    <h1>Edit TraductionSource</h1>

    {{ include('traduction_source/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('traduction_source_index') }}">back to list</a>

    {{ include('traduction_source/_delete_form.html.twig') }}
{% endblock %}

Crowdin/templates/traduction_source/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}TraductionSource index
{% endblock %}

{% block body %}
	<h1>Translation Source index</h1>

	<table class="table">
		<thead>
			<tr>
				<th>Project</th>
				<th>Source</th>
				<th>Language</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for language in app.user.languages %}
				{% for traduction_source in traduction_sources %}
					{% if language.languageName ==  traduction_source.projectId.languageId.LanguageName %}
						<tr>
							<td>{{	traduction_source.projectid.name  }}</td>
							<td>{{ traduction_source.source }}</td>
							<td>{{	traduction_source.projectid.LanguageId.LanguageName  }}</td>
							<td>
								<a href="{{ path('traduction_source_show', {'id': traduction_source.id}) }}">show</a>
								{% if is_granted('edit', traduction_source) %}
									<a href="{{ path('traduction_source_edit', {'id': traduction_source.id}) }}">edit</a>
								</td>
							</td>
							<td>
								{{ include('traduction_source/_delete_form.html.twig') }}
							</td>
						{% endif %}
					</tr>
				{% endif %}
			{% endfor %}
		{% endfor %}
		{{ knp_pagination_render(traduction_sources) }}
	</tbody>
</table>{% endblock %}

Crowdin/templates/traduction_source/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New TraductionSource{% endblock %}

{% block body %}
    <h1>Create new TraductionSource</h1>

    {{ include('traduction_source/_form.html.twig') }}

    <a href="{{ path('traduction_source_index') }}">back to list</a>
{% endblock %}

Crowdin/templates/traduction_source/newCSV.html.twig
{% extends 'base.html.twig' %}

{% block title %}New TraductionSource{% endblock %}

{% block body %}
    <h1>Create new TraductionSource</h1>

    {{ include('traduction_source/_form.html.twig') }}

    <a href="{{ path('traduction_source_index') }}">back to list</a>
{% endblock %}

Crowdin/templates/traduction_source/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}TraductionSource
{% endblock %}

{% block body %}
	<h1>Translations for
		{{traduction_source.source}}</h1>


	<a href="{{ path('traduction_target_new', {'id': traduction_source.id}) }}">New Translation</a>

	<table class="table">

		<thead>
			<tr>
				<th>Language</th>
				<th>Translation</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
			{% for traduction_target in traduction_source.traductionTargets %}
				<tr>
					<td>{{ traduction_target.languageId.LanguageName }}</td>
					<td>{{ traduction_target.target }}</td>
					<td>
						<a href="{{ path('traduction_target_show', {'id': traduction_target.id}) }}">show</a>
						{% if is_granted('edit', traduction_target) %}
							<a href="{{ path('traduction_target_edit', {'id': traduction_target.id}) }}">edit</a>
						</td>
					</td>
					<td>
						{{ include('traduction_target/_delete_form.html.twig') }}
					</td>
				{% endif %}
			</tr>
		{% endfor %}
	</tbody>
</table>

<br><br>

<a href="{{ path('traduction_source_index') }}">back to list</a>{% endblock %}