Crowdin/src/Entity/TraductionSource.php
<?php

namespace App\Entity;

use App\Entity\Project;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TraductionSourceRepository")
 */
class TraductionSource
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Project", inversedBy="traductionSources")
     * @ORM\JoinColumn(nullable=false)
     */
    private $project;

    /**
     * @ORM\Column(type="string", length=255,  nullable=true)
     */
	private $source;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\TraductionTarget", mappedBy="traduction_source", orphanRemoval=true)
     */
    private $traductionTargets;

    public function __construct()
    {
        $this->traductionTargets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProjectId(): ?Project
    {
        return $this->project;
    }

    public function setProjectId(?Project $project): self
    {
        $this->project = $project;

        return $this;
	}
	
	public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): self
    {
        $this->project = $project;

        return $this;
    }

    public function getSource(): ?string
    {
        return $this->source;
    }

    public function setSource(string $source): self
    {
        $this->source = $source;

        return $this;
	}


    /**
     * @return Collection|TraductionTarget[]
     */
    public function getTraductionTargets(): Collection
    {
        return $this->traductionTargets;
    }

    public function addTraductionTarget(TraductionTarget $traductionTarget): self
    {
        if (!$this->traductionTargets->contains($traductionTarget)) {
            $this->traductionTargets[] = $traductionTarget;
            $traductionTarget->setTraductionSourceId($this);
        }

        return $this;
    }

    public function removeTraductionTarget(TraductionTarget $traductionTarget): self
    {
        if ($this->traductionTargets->contains($traductionTarget)) {
            $this->traductionTargets->removeElement($traductionTarget);
            // set the owning side to null (unless already changed)
            if ($traductionTarget->getTraductionSourceId() === $this) {
                $traductionTarget->setTraductionSourceId(null);
            }
        }

        return $this;
	}
	public function __toString()
    {
        return $this->source;
    }

}

Crowdin/src/Entity/TraductionTarget.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TraductionTargetRepository")
 */
class TraductionTarget
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Language", inversedBy="traductionTargets")
     * @ORM\JoinColumn(nullable=false)
     */
    public $language;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TraductionSource", inversedBy="traductionTargets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $traduction_source;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $target;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="traductionTargets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_id;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLanguageId(): ?Language
    {
        return $this->language;
    }

	public function getLanguage(): ?Language
    {
        return $this->language;
	}
	
    public function setLanguageId(?Language $language): self
    {
        $this->language = $language;

        return $this;
	}
	
	public function setLanguage(?Language $language): self
    {
        $this->language = $language;

        return $this;
    }


    public function getTraductionSourceId(): ?TraductionSource
    {
        return $this->traduction_source;
    }

    public function setTraductionSourceId(?TraductionSource $traduction_source): self
    {
        $this->traduction_source = $traduction_source;

        return $this;
	}
	
	public function getTraductionSource(): ?TraductionSource
    {
        return $this->traduction_source;
    }

    public function setTraductionSource(?TraductionSource $traduction_source): self
    {
        $this->traduction_source = $traduction_source;

        return $this;
    }

    public function getTarget(): ?string
    {
        return $this->target;
    }

    public function setTarget(string $target): self
    {
        $this->target = $target;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user_id;
    }

    public function setUser(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
	}

	public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
	}
	
	public function __toString()
    {
        return $this->target;
    }

}

Crowdin/src/Form/TraductionTargetType.php
<?php

namespace App\Form;

use App\Entity\TraductionTarget;
use App\Entity\Language;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class TraductionTargetType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('target')
            ->add('language', EntityType::class, [
				'class' => Language::class,
				'choice_label' => function(Language $language) {
                    return sprintf('%s', $language->getLanguageName());
                }
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => TraductionTarget::class,
        ]);
    }
}

Crowdin/src/Controller/TraductionTargetController.php
<?php

namespace App\Controller;

use App\Entity\TraductionTarget;
use App\Entity\TraductionSource;
use App\Manager\TraductionTargetManager;
use App\Form\TraductionTargetType;
use App\Repository\TraductionTargetRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;


/**
 * @Route("/traduction/target")
 */
class TraductionTargetController extends AbstractController
{
    /**
     * @Route("/", name="traduction_target_index", methods={"GET"})
     */
    public function index(TraductionTargetRepository $repository, Request $request, PaginatorInterface $paginator): Response
    {

		$data =  $repository->findAll();
		$traductionTargets= $paginator->paginate(
		$data, // Requête contenant les données à paginer (ici nos articles)
			$request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
			20 // Nombre de résultats par page
		);


        return $this->render('traduction_target/index.html.twig', [
            'traduction_targets' =>$traductionTargets,
        ]);
    }

    /**
     * @Route("/new/{id}", name="traduction_target_new", methods={"GET","POST"})
     */
    public function new(TraductionSource $traductionSource, Request $request, TraductionTargetManager $manager): Response
    {
		$traductionTarget = new TraductionTarget();
		$traductionTarget->setUser($this->getUser());
		$traductionTarget->setTraductionSourceId($traductionSource);
        $form = $this->createForm(TraductionTargetType::class, $traductionTarget);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
			$manager->add($traductionTarget);
            $manager->save();

            return $this->redirectToRoute('traduction_target_index');
        }

        return $this->render('traduction_target/new.html.twig', [
            'traduction_target' => $traductionTarget,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="traduction_target_show", methods={"GET"})
     */
    public function show(TraductionTarget $traductionTarget): Response
    {
        return $this->render('traduction_target/show.html.twig', [
            'traduction_target' => $traductionTarget,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="traduction_target_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, TraductionTarget $traductionTarget, TraductionTargetManager $manager): Response
    {
		$this->denyAccessUnlessGranted('edit', $traductionTarget);
        $form = $this->createForm(TraductionTargetType::class, $traductionTarget);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $manager->save();

            return $this->redirectToRoute('traduction_target_index');
        }

        return $this->render('traduction_target/edit.html.twig', [
            'traduction_target' => $traductionTarget,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="traduction_target_delete", methods={"DELETE"})
     */
    public function delete(Request $request, TraductionTarget $traductionTarget, TraductionTargetManager $manager): Response
    {
		$this->denyAccessUnlessGranted('delete', $traductionTarget);
        if ($this->isCsrfTokenValid('delete'.$traductionTarget->getId(), $request->request->get('_token'))) {
			$manager->delete($traductionTarget);
			$manager->save();
        }

		return $this->redirectToRoute('traduction_target_index');
	}
}

Crowdin/templates/traduction_target/_delete_form.html.twig
<form method="post" action="{{ path('traduction_target_delete', {'id': traduction_target.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ traduction_target.id) }}">
    <button class="btn">Delete</button>
</form>

Crowdin/templates/traduction_target/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

Crowdin/templates/traduction_target/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit TraductionTarget{% endblock %}

{% block body %}
    <h1>Edit TraductionTarget</h1>

    {{ include('traduction_target/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('traduction_target_index') }}">back to list</a>

    {{ include('traduction_target/_delete_form.html.twig') }}
{% endblock %}

Crowdin/templates/traduction_target/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}TraductionTarget index
{% endblock %}

{% block body %}
	<h1>Traductions index</h1>


	<table class="table">
		<thead>
			<tr>
				<th>Project</th>
				<th>Author</th>
				<th>Source</th>
				<th>Language</th>
				<th>Translation</th>
				<th>Language</th>
				<th>actions</th>
			</tr>
		</thead>
		<tbody>
				{% for traduction_target in traduction_targets %}
						<tr>
							<td>{{ traduction_target.traductionSourceId.projectId.name  }}</td>
							<td>{{ traduction_target.traductionSourceId.projectId.user.pseudo }}</td>
							<td>{{ traduction_target.traductionSourceId.source }}</td>
							<td>{{ traduction_target.traductionSourceId.projectId.languageId.LanguageName  }}</td>
							<td>{{ traduction_target.target }}</td>
							<td>{{ traduction_target.languageId.LanguageName }}</td>
							<td>
								{% if is_granted('edit', traduction_target) %}
									<a href="{{ path('traduction_target_edit', {'id': traduction_target.id}) }}">edit</a>
								</td>
							</td>
							<td>
								{{ include('traduction_target/_delete_form.html.twig') }}
							</td>
						{% endif %}
					</tr>
			
		{% endfor %}
	</tbody>
</table>{% endblock %}

Crowdin/templates/traduction_target/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New TraductionTarget{% endblock %}

{% block body %}
    <h1>Create new TraductionTarget</h1>

    {{ include('traduction_target/_form.html.twig') }}

    <a href="{{ path('traduction_target_index') }}">back to list</a>
{% endblock %}

Crowdin/templates/traduction_target/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}TraductionTarget{% endblock %}

{% block body %}
    <h1>TraductionTarget</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ traduction_target.id }}</td>
            </tr>
            <tr>
                <th>Target</th>
                <td>{{ traduction_target.target }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('traduction_target_index') }}">back to list</a>

    <a href="{{ path('traduction_target_edit', {'id': traduction_target.id}) }}">edit</a>

    {{ include('traduction_target/_delete_form.html.twig') }}
{% endblock %}